Repository LiskHQ/lisk-docs, pull requests merged in 2018-12, with the labels that each got.

#140 Add flag for unprocessed/unsigned tx - Closes #110, #139
  user-guide/commands/commands.md
Labels: commander

#125 Add references to product releases - Partially closes #111
  introduction.md
Labels: :eye: pending review, core

#128 Add "What is Lisk Core?" video to Lisk Core introduction page - Closes #20
  introduction.md
Labels: :eye: pending review, core

#134 Update Source Upgrade section, Closes #133
  upgrade/source/upgrade-source.md
Labels: :eye: pending review, core

#141 Add new commands, delegate get voters and votes - Closes #137
  user-guide/commands/commands.md
Labels: :eye: pending review, commander

#142 Add data field option - Closes #138
  user-guide/commands/commands.md
Labels: :eye: pending review, commander

#150 Changed rm -rF to rm -rf - Closes #149
  upgrade/source/upgrade-source.md
Labels: :eye: pending review, bug, core
