Repository LiskHQ/lisk-docs, pull requests merged in 2018-11, with the labels that each got.

#100 Update release note, remove old notes, Closes #99
  setup/install/docker/installation-docker.md
  setup/install/source/installation-source.md
  user-guide/configuration/configuration.md
Labels: core

#102 Docker files move, Closes #101
  setup/install/docker/installation-docker.md
Labels: core

#95 Rewording in configuration.md - Closes #19
  user-guide/configuration/configuration.md
Labels: :eye: pending review, core

#106 Add new available options for redis, Closes #105
  user-guide/administration/source/admin-source.md
Labels: :eye: pending review, core

#104 Update forging example (docker) - Closes #103
  user-guide/administration/docker/admin-docker.md
Labels: :eye: pending review, core

#108 Fix table of contents (Commander: setup)
  setup/setup.md
Labels: commander

#121 Update required node version to >=8 - Closes #119
  setup/setup.md
Labels: :eye: pending review, elements

#115 Add section with references to older docs versions - Partially closes #111
  introduction.md
Labels: :eye: pending review, core

#123 Add option for sodium-native usage - Closes #120
  packages/cryptography/cryptography.md
Labels: :eye: pending review, elements
