Repository LiskHQ/lisk-docs, pull requests merged in 2019-08, with the labels that each got.

#317 Add Discord links, remove gitter and rocket chat, Partially closes #316
  introduction.md
  troubleshooting.md
Labels: :eye: pending review, core

#319 Add Discord links, remove gitter and rocket chat, Partially closes #316
  resources.md
Labels: :eye: pending review, start

#331 Add additional instructions to SDK tutorials, closes #330
  tutorials/cashback.md
  tutorials/hello-world.md
Labels: :eye: pending review, start

#333 Update version numbers for lisk client cdn, Closes #332
  introduction.md
Labels: elements, sdk

#335 Add curl as dependency, Closes #327
  setup.md
Labels: :eye: pending review, sdk

#338 Add dependencies for sdk
  setup.md
Labels: :eye: pending review, sdk

#337 Add missing Core dependencies, Closes #336
  setup/source.md
Labels: :eye: pending review, core

#341 replace interactive by imperative commands
  tutorials/cashback.md
Labels: :eye: pending review, start

#343 add BaseModule import
  lisk-framework/introduction.md
Labels: :eye: pending review, sdk

#345 edit transaction.broadcast information. Explicit the JSON usage
  packages/api-client/transactions.md
Labels: :eye: pending review, elements
