Repository LiskHQ/lisk-docs, pull requests merged in 2020-12, with the labels that each got.

#804 Minor updates in SDK docs 4.0.0 - Closes #782
  modules/ROOT/pages/guides/app-development/custom-transactions.adoc
  modules/ROOT/pages/guides/app-development/frontend.adoc
  modules/ROOT/pages/guides/app-development/interact-with-api.adoc
  modules/ROOT/pages/guides/app-development/launch.adoc
  modules/ROOT/pages/guides/app-development/test-transaction.adoc
  modules/ROOT/pages/guides/node-management/enable-ssl.adoc
  modules/ROOT/pages/guides/node-management/forging.adoc
  modules/ROOT/pages/references/api-specification.adoc
  modules/ROOT/pages/references/changelog.adoc
  modules/ROOT/pages/references/config.adoc
  modules/ROOT/pages/references/index.adoc
  modules/ROOT/pages/references/lisk-commander/commands.adoc
  modules/ROOT/pages/references/lisk-commander/index.adoc
  modules/ROOT/pages/references/lisk-commander/sensitive-inputs.adoc
  modules/ROOT/pages/references/lisk-elements/api-client.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/node.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/transactions.adoc
  modules/ROOT/pages/references/lisk-elements/bft.adoc
  modules/ROOT/pages/references/lisk-elements/chain.adoc
  modules/ROOT/pages/references/lisk-elements/constants.adoc
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
  modules/ROOT/pages/references/lisk-elements/dpos.adoc
  modules/ROOT/pages/references/lisk-elements/index.adoc
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
  modules/ROOT/pages/references/lisk-elements/passphrase.adoc
  modules/ROOT/pages/references/lisk-elements/transactions.adoc
  modules/ROOT/pages/references/lisk-framework/index.adoc
  modules/ROOT/pages/setup.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/pages/tutorials/supply-chain/index.adoc
  modules/ROOT/pages/tutorials/supply-chain/part1.adoc
  modules/ROOT/pages/tutorials/supply-chain/part2.adoc
  modules/ROOT/pages/tutorials/supply-chain/part3.adoc
  modules/ROOT/pages/tutorials/supply-chain/part4.adoc
Labels: component: sdk, type: bug

#819 Fix previous link on tutorial index in SDK docs 3.0.2 - Closes #818
  modules/ROOT/pages/tutorials/index.adoc
Labels: component: sdk, type: bug

#821 Fix previous links on tutorial index in SDK docs 4.0.0 - Closes #820
  modules/ROOT/pages/tutorials/index.adoc
Labels: component: sdk, type: bug

#850 Update navigation in Core 2.x docs - Closes #847
  modules/ROOT/nav.adoc
  modules/ROOT/pages/setup/application.adoc
  modules/ROOT/pages/setup/commander.adoc
  modules/ROOT/pages/setup/docker.adoc
  modules/ROOT/pages/setup/index.adoc
  modules/ROOT/pages/setup/source.adoc
Labels: component: core

#851 Update navigation and titles in SDK docs - Closes #848
  modules/ROOT/nav.adoc
  modules/ROOT/pages/architecture/index.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/references/lisk-commander/index.adoc
  modules/ROOT/pages/references/lisk-elements/index.adoc
  modules/ROOT/pages/tutorials/index.adoc
Labels: component: sdk

#854 Update navigation - Closes #852
  modules/ROOT/nav.adoc
  modules/ROOT/pages/setup/docker.adoc
  modules/ROOT/pages/setup/index.adoc
  modules/ROOT/pages/setup/source.adoc
  modules/ROOT/pages/update/docker.adoc
  modules/ROOT/pages/update/source.adoc
Labels: component: service

#835 Update meta descriptions in Core docs 3.0.2 beta-2 - Closes #832
  modules/ROOT/pages/management/account-management.adoc
  modules/ROOT/pages/management/application.adoc
  modules/ROOT/pages/management/configuration.adoc
  modules/ROOT/pages/management/index.adoc
  modules/ROOT/pages/reference/api.adoc
  modules/ROOT/pages/reference/cli.adoc
  modules/ROOT/pages/reference/index.adoc
Labels: component: core, type: bug, type: update

#830 Add Core protocol module - Closes #825
  modules/ROOT/assets/images/ReclaimAsset.png
  modules/ROOT/pages/index.adoc
Labels: component: core

#829 Update meta descriptions in SDK docs v5 - Closes #828
  modules/ROOT/pages/architecture/communication-architecture.adoc
  modules/ROOT/pages/architecture/index.adoc
  modules/ROOT/pages/architecture/off-chain-architecture.adoc
  modules/ROOT/pages/architecture/on-chain-architecture.adoc
  modules/ROOT/pages/consensus.adoc
  modules/ROOT/pages/guides/app-development/configuration.adoc
  modules/ROOT/pages/guides/app-development/custom-transactions.adoc
  modules/ROOT/pages/guides/app-development/interact-with-api.adoc
  modules/ROOT/pages/guides/app-development/launch.adoc
  modules/ROOT/pages/guides/app-development/setup.adoc
  modules/ROOT/pages/guides/app-development/test-transaction.adoc
  modules/ROOT/pages/guides/index.adoc
  modules/ROOT/pages/guides/node-management/forging.adoc
  modules/ROOT/pages/guides/node-management/index.adoc
  modules/ROOT/pages/guides/node-management/logging.adoc
  modules/ROOT/pages/references/changelog.adoc
  modules/ROOT/pages/references/lisk-commander/commands.adoc
  modules/ROOT/pages/references/lisk-commander/sensitive-inputs.adoc
  modules/ROOT/pages/references/lisk-elements/chain.adoc
  modules/ROOT/pages/references/lisk-elements/client.adoc
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
  modules/ROOT/pages/references/lisk-elements/index.adoc
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
  modules/ROOT/pages/references/lisk-elements/passphrase.adoc
  modules/ROOT/pages/references/lisk-elements/transaction-pool.adoc
  modules/ROOT/pages/references/lisk-elements/transactions.adoc
  modules/ROOT/pages/references/lisk-elements/validator.adoc
  modules/ROOT/pages/references/lisk-framework/config.adoc
  modules/ROOT/pages/references/lisk-framework/http-api-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/index.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/pages/tutorials/index.adoc
  modules/ROOT/pages/tutorials/supply-chain/index.adoc
  modules/ROOT/pages/tutorials/supply-chain/part1.adoc
  modules/ROOT/pages/tutorials/supply-chain/part2.adoc
  modules/ROOT/pages/tutorials/supply-chain/part3.adoc
  modules/ROOT/pages/tutorials/supply-chain/part4.adoc
Labels: component: sdk, type: update

#863 Adjust introductory paragraph
  modules/protocol/pages/index.adoc
Labels: component: sdk

#856 Add new page about rpc endpoints - Closes #838
  modules/ROOT/nav.adoc
  modules/ROOT/pages/architecture/communication-architecture.adoc
  modules/ROOT/pages/quickstart.adoc
  modules/ROOT/pages/references/lisk-elements/api-client.adoc
  modules/ROOT/pages/references/lisk-elements/client.adoc
  modules/ROOT/pages/rpc-endpoints.adoc
Labels: component: sdk

#869 Bump sdk version to 5.0.1 - Closes #859
  antora.yml
  modules/ROOT/pages/architecture/off-chain-architecture.adoc
  modules/ROOT/pages/architecture/on-chain-architecture.adoc
  modules/ROOT/pages/guides/app-development/configuration.adoc
  modules/ROOT/pages/guides/app-development/custom-transactions.adoc
  modules/ROOT/pages/guides/app-development/launch.adoc
  modules/ROOT/pages/references/changelog.adoc
  modules/ROOT/pages/references/lisk-elements/index.adoc
Labels: component: sdk

#861 Update hello world tutorial - Closes #858
  modules/ROOT/assets/images/tutorials/account-details.png
  modules/ROOT/assets/images/tutorials/create-account.png
  modules/ROOT/assets/images/tutorials/faucet.png
  modules/ROOT/assets/images/tutorials/hello-counter.png
  modules/ROOT/assets/images/tutorials/home.png
  modules/ROOT/assets/images/tutorials/send-hello.png
  modules/ROOT/assets/images/tutorials/transfer.png
  modules/ROOT/pages/tutorials/hello-world.adoc
Labels: component: sdk

#831 Add strong password note to passphrase encryption
  modules/ROOT/pages/guides/node-management/forging.adoc
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
Labels: type: update

#875 Add reference page for the sequence module - Closes #866
  modules/ROOT/nav.adoc
  modules/ROOT/pages/sequence-module.adoc
Labels: component: sdk

#874 Update guide 'Configuring a blockchain application`
  modules/ROOT/nav.adoc
  modules/ROOT/pages/architecture/index.adoc
  modules/ROOT/pages/guides/app-development/configuration.adoc
  modules/ROOT/pages/rpc-endpoints.adoc
Labels: component: sdk

#880 Add keys module reference - Closes #867
  modules/ROOT/pages/keys-module.adoc
Labels: component: sdk
