Repository LiskHQ/lisk-docs, pull requests merged in 2020-08, with the labels that each got.

#682 Fix wrong parameter, Closes #681
  modules/ROOT/pages/management/forging.adoc
Labels: core

#685 Minor update in config pages in Core docs 2.1.6 - Closes #684
  modules/ROOT/pages/management/configuration.adoc
  modules/ROOT/pages/reference/config.adoc
Labels: bug, core

#689 Improve breakpoints styling - Closes #650
  build/ui-bundle.zip
  src/css/extensions/site-extra.css
  src/css/main.css
  src/css/vars.css
Labels: ui

#712 Update broadcast guide - Closes #709
  modules/ROOT/pages/guides/app-development/broadcast.adoc
Labels: sdk

#713 Update frontend guide - Closes #710
  modules/ROOT/assets/images/Screenshot 2020-08-18 at 13.30.17.png
  modules/ROOT/assets/images/hello-accounts.png
  modules/ROOT/assets/images/hello-blocks.png
  modules/ROOT/assets/images/hello-faucet.png
  modules/ROOT/assets/images/hello-hello.png
  modules/ROOT/assets/images/hello-hello_accounts.png
  modules/ROOT/assets/images/hello-hello_transactions.png
  modules/ROOT/assets/images/hello-index.png
  modules/ROOT/assets/images/hello-new_account.png
  modules/ROOT/assets/images/hello-transactions.png
  modules/ROOT/assets/images/hello-transfer.png
  modules/ROOT/pages/guides/app-development/frontend.adoc
Labels: sdk

#716 Update the launch guide - Closes #714
  modules/ROOT/pages/guides/app-development/launch.adoc
Labels: sdk

#703 Update config guide - Closes #699
  modules/ROOT/pages/guides/app-development/configuration.adoc
Labels: sdk

#708 Update api guide - Closes #706
  modules/ROOT/pages/guides/app-development/interact-with-api.adoc
Labels: sdk

#704 Update the custom transactions guide - Closes #555
  modules/ROOT/nav.adoc
  modules/ROOT/pages/guides/app-development/custom-transactions.adoc
Labels: sdk

#707 Update testing guide - Closes #705
  modules/ROOT/pages/guides/app-development/test-transaction.adoc
Labels: sdk

#702 Update hello tutorial - Closes #700
  modules/ROOT/pages/tutorials/hello-world.adoc
Labels: sdk

#718 Update management guides - Closes #717
  modules/ROOT/pages/guides/node-management/api-access.adoc
  modules/ROOT/pages/guides/node-management/enable-ssl.adoc
  modules/ROOT/pages/guides/node-management/forging.adoc
Labels: sdk

#721 Update the supply chain tutorial - Closes #719
  modules/ROOT/pages/tutorials/supply-chain/index.adoc
  modules/ROOT/pages/tutorials/supply-chain/part1.adoc
  modules/ROOT/pages/tutorials/supply-chain/part2.adoc
  modules/ROOT/pages/tutorials/supply-chain/part3.adoc
  modules/ROOT/pages/tutorials/supply-chain/part4.adoc
Labels: sdk

#722 Add sections about transaction fees - Closes #559
  modules/ROOT/pages/guides/app-development/broadcast.adoc
  modules/ROOT/pages/guides/app-development/custom-transactions.adoc
  modules/ROOT/pages/index.adoc
Labels: sdk
