Repository LiskHQ/lisk-docs, pull requests merged in 2020-01, with the labels that each got.

#382 Add a git checkout master step to the Docker docs
  modules/ROOT/pages/setup/docker.adoc
Labels: core, status: pending review

#405 meta descriptions & updates/error corrections
  modules/ROOT/pages/configuration.adoc
  modules/ROOT/pages/customize.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/setup.adoc
  modules/ROOT/pages/tutorials/cashback.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/pages/tutorials/index.adoc
  modules/ROOT/pages/tutorials/transport.adoc
  modules/ROOT/pages/tutorials/transport0.adoc
  modules/ROOT/pages/tutorials/transport1.adoc
  modules/ROOT/pages/tutorials/transport2.adoc
  modules/ROOT/pages/tutorials/transport3.adoc
Labels: status: pending review

#421 Remove New Relic - Closes #406
  modules/ROOT/pages/monitoring.adoc
Labels: status: ready
