Repository LiskHQ/lisk-docs, pull requests merged in 2020-03, with the labels that each got.

#468 Updated minor changes/command changes in binary.adoc - Closes #467
  modules/ROOT/pages/setup/binary.adoc
Labels: core

#483 Fix typos - Closes #481
  build/ui-bundle.zip
  src/partials/footer-content.hbs
  src/partials/header-content.hbs
Labels: ui

#470 SDK minor changes and command changes - closes #469, #471
  modules/ROOT/pages/getting-started.adoc
  modules/ROOT/pages/reference/index.adoc
  modules/ROOT/pages/setup.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/partials/install-node.adoc
Labels: sdk

#495 Unify headings titles and breadcrumbs for SDK 3.0.2 - closes#479
  modules/ROOT/assets/images/banner_commander.png
  modules/ROOT/assets/images/banner_core.png
  modules/ROOT/assets/images/banner_elements.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/getting-started.adoc
  modules/ROOT/pages/guides/index.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/reference/api.adoc
  modules/ROOT/pages/reference/changelog.adoc
  modules/ROOT/pages/reference/config.adoc
  modules/ROOT/pages/reference/lisk-commander/index.adoc
  modules/ROOT/pages/reference/lisk-commander/user-guide.adoc
  modules/ROOT/pages/reference/lisk-commander/user-guide/commands.adoc
  modules/ROOT/pages/reference/lisk-commander/user-guide/sensitive-inputs.adoc
  modules/ROOT/pages/reference/lisk-elements/index.adoc
  modules/ROOT/pages/reference/lisk-elements/packages/api-client.adoc
  modules/ROOT/pages/reference/lisk-elements/packages/client.adoc
  modules/ROOT/pages/reference/lisk-elements/packages/constants.adoc
  modules/ROOT/pages/reference/lisk-elements/packages/cryptography.adoc
  modules/ROOT/pages/reference/lisk-elements/packages/index.adoc
  modules/ROOT/pages/reference/lisk-elements/packages/p2p.adoc
  modules/ROOT/pages/reference/lisk-elements/packages/passphrase.adoc
  modules/ROOT/pages/reference/lisk-elements/packages/transaction-pool.adoc
  modules/ROOT/pages/reference/lisk-elements/packages/transactions.adoc
  modules/ROOT/pages/reference/lisk-elements/packages/validator.adoc
  modules/ROOT/pages/reference/lisk-framework/index.adoc
  modules/ROOT/pages/setup.adoc
  modules/ROOT/pages/tutorials/cashback.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/pages/tutorials/index.adoc
  modules/ROOT/pages/tutorials/transport.adoc
  modules/ROOT/pages/tutorials/transport0.adoc
  modules/ROOT/pages/tutorials/transport1.adoc
  modules/ROOT/pages/tutorials/transport2.adoc
  modules/ROOT/pages/tutorials/transport3.adoc
  modules/ROOT/partials/install-node.adoc
  modules/ROOT/partials/install-postgres.adoc
Labels: bug, sdk

#500 Add guide: Enable forging - Closes #498
  modules/ROOT/pages/guides/forging.adoc
Labels: sdk

#503 Fix capitalisation issues in SDK 3.0.2 new - closes #497
  modules/ROOT/pages/guides/configuration.adoc
Labels: bug, sdk

#494 Add new guide: launch a blockchain application - Closes #386
  modules/ROOT/assets/images/launch-2_nodes.png
  modules/ROOT/assets/images/launch-3_nodes.png
  modules/ROOT/assets/images/launch-seed_node.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/guides/launch.adoc
Labels: sdk

#513 Update customize guide - Closes #512
  modules/ROOT/pages/guides/customize.adoc
Labels: sdk

#511 Update config guide - Closes #510
  modules/ROOT/pages/guides/configuration.adoc
Labels: sdk
