Repository LiskHQ/lisk-docs, pull requests merged in 2020-05, with the labels that each got.

#581 Correct outdated errors in update binary, commander, docker and source pages in Core docs - closes 579
  modules/ROOT/pages/update/binary.adoc
  modules/ROOT/pages/update/commander.adoc
  modules/ROOT/pages/update/docker.adoc
  modules/ROOT/pages/update/source.adoc
Labels: bug, core

#584 Remove all links to migration page and update nav page in Core docs - closes #582
  modules/ROOT/nav.adoc
  modules/ROOT/pages/index.adoc
Labels: bug, core

#586 Update blocks section in protocol documentation
  modules/ROOT/pages/blocks.adoc
Labels: protocol

#588 Fix writing and add links
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/appendix.adoc
  modules/ROOT/pages/index.adoc
Labels: protocol

#580 Update config reference - Closes #553
  modules/ROOT/pages/reference/config.adoc
Labels: sdk

#583 Update API reference - Closes #554
  modules/ROOT/pages/reference/api.adoc
Labels: sdk

#597 Dev antora
  build/ui-bundle.zip
  src/css/base.css
  src/css/extensions/highlight-solarized_dark.css
  src/css/extensions/hightlight-extra.css
  src/css/extensions/site-extra.css
  src/css/footer.css
  src/css/header.css
  src/css/site.css
  src/css/typeface-basiercircle.css
  src/css/vars.css
  src/font/basiersquare-regular-webfont.woff
  src/font/basiersquare-regular-webfont.woff2
  src/img/icon-discord.svg
  src/partials/head-title.hbs
  src/partials/header-content.hbs
  src/partials/page-versions.hbs
  src/partials/toolbar.hbs
Labels: ui

#594 Insert missing image and update case changes in Core docs 2.1.6 - closes #592
  modules/ROOT/pages/index.adoc
Labels: bug, core

#608 Changed order of testnet and mainnet in nav.adoc - closes #607
  modules/ROOT/nav.adoc
Labels: bug, core

#596 Update issues in binary commander docker and source pages in core docs 2.1.5 - closes #595
  modules/ROOT/pages/setup/binary.adoc
  modules/ROOT/pages/setup/commander.adoc
  modules/ROOT/pages/setup/docker.adoc
  modules/ROOT/pages/setup/source.adoc
Labels: bug, core

#606 Update title in config page in Core docs 2.1.6 - closes #605
  modules/ROOT/nav.adoc
  modules/ROOT/pages/management/configuration.adoc
Labels: bug, core

#615 Add page aliases - Closes #614
  modules/ROOT/pages/getting-started.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/interact-with-network.adoc
  modules/ROOT/pages/management/binary.adoc
  modules/ROOT/pages/management/commander.adoc
  modules/ROOT/pages/management/docker.adoc
  modules/ROOT/pages/management/source.adoc
  modules/ROOT/pages/reference/api-mainnet.adoc
  modules/ROOT/pages/reference/api.adoc
  modules/ROOT/pages/reference/config.adoc
  modules/ROOT/pages/update/binary.adoc
  modules/ROOT/pages/update/commander.adoc
  modules/ROOT/pages/update/docker.adoc
  modules/ROOT/pages/update/source.adoc
Labels: core

#600 Update issues in management binary commander docker and source pages in core docs 2.1.5 - closes #599
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/management/binary.adoc
  modules/ROOT/pages/management/commander.adoc
  modules/ROOT/pages/management/docker.adoc
  modules/ROOT/pages/management/source.adoc
Labels: bug, core

#612 Add and update meta descriptions in Core docs 2.1.6 - closes #611
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/interact-with-network.adoc
  modules/ROOT/pages/management/api-access.adoc
  modules/ROOT/pages/management/commander.adoc
  modules/ROOT/pages/management/docker.adoc
  modules/ROOT/pages/management/forging.adoc
  modules/ROOT/pages/management/logs.adoc
  modules/ROOT/pages/management/source.adoc
  modules/ROOT/pages/management/ssl.adoc
  modules/ROOT/pages/migration.adoc
  modules/ROOT/pages/monitoring.adoc
  modules/ROOT/pages/reference/api-mainnet.adoc
  modules/ROOT/pages/reference/api.adoc
  modules/ROOT/pages/reference/config.adoc
Labels: bug, core
