Repository LiskHQ/lisk-docs, pull requests merged in 2020-04, with the labels that each got.

#519 Update title in guides - closes#516
  modules/ROOT/nav.adoc
  modules/ROOT/pages/guides/broadcast.adoc
  modules/ROOT/pages/guides/configuration.adoc
  modules/ROOT/pages/guides/customize.adoc
  modules/ROOT/pages/guides/frontend.adoc
  modules/ROOT/pages/guides/index.adoc
  modules/ROOT/pages/guides/launch.adoc
  modules/ROOT/pages/reference/changelog.adoc
  modules/ROOT/pages/reference/index.adoc
  modules/ROOT/pages/reference/lisk-elements/transaction-pool.adoc
  modules/ROOT/pages/reference/lisk-framework/index.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/pages/tutorials/index.adoc
Labels: bug, sdk

#518 Update test guide - Closes #514
  modules/ROOT/pages/guides/test.adoc
Labels: sdk

#543 Update title tag - Closes #525
  src/partials/head-title.hbs
Labels: ui

#544 Remove best practice page - Closes #534
  modules/ROOT/nav.adoc
  modules/ROOT/pages/best-practices.adoc
  modules/ROOT/pages/guides/customize.adoc
  modules/ROOT/pages/guides/forging.adoc
  modules/ROOT/pages/tutorials/index.adoc
Labels: sdk

#537 Open external links in new tab - Closes #523
  modules/ROOT/pages/guides/broadcast.adoc
  modules/ROOT/pages/guides/configuration.adoc
  modules/ROOT/pages/guides/customize.adoc
  modules/ROOT/pages/guides/frontend.adoc
  modules/ROOT/pages/guides/index.adoc
  modules/ROOT/pages/guides/interact.adoc
  modules/ROOT/pages/guides/launch.adoc
  modules/ROOT/pages/guides/test.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/reference/api.adoc
  modules/ROOT/pages/reference/changelog.adoc
  modules/ROOT/pages/reference/index.adoc
  modules/ROOT/pages/reference/lisk-commander/commands.adoc
  modules/ROOT/pages/reference/lisk-commander/index.adoc
  modules/ROOT/pages/reference/lisk-commander/lisk-core.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/accounts.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/blocks.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/dapps.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/delegates.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/node.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/peers.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/signatures.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/transactions.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/voters.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/votes.adoc
  modules/ROOT/pages/reference/lisk-elements/cryptography.adoc
  modules/ROOT/pages/reference/lisk-elements/index.adoc
  modules/ROOT/pages/reference/lisk-elements/passphrase.adoc
  modules/ROOT/pages/reference/lisk-framework/index.adoc
  modules/ROOT/pages/setup.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/pages/tutorials/transport0.adoc
  modules/ROOT/pages/tutorials/transport1.adoc
  modules/ROOT/pages/tutorials/transport2.adoc
  modules/ROOT/pages/tutorials/transport3.adoc
  modules/ROOT/partials/install-node.adoc
  modules/ROOT/partials/install-postgres.adoc
Labels: sdk

#564 Update amend add content to reference pages in SDK docs - closes #550
  modules/ROOT/nav.adoc
  modules/ROOT/pages/guides/forging.adoc
  modules/ROOT/pages/reference/index.adoc
  modules/ROOT/pages/reference/lisk-elements/api-client/dapps.adoc
  modules/ROOT/pages/reference/lisk-elements/client.adoc
  modules/ROOT/pages/reference/lisk-elements/index.adoc
  modules/ROOT/pages/reference/lisk-elements/transactions.adoc
Labels: bug, sdk

#578 Update framework - Closes #574
  modules/ROOT/pages/reference/lisk-framework/index.adoc
Labels: sdk

#571 Update issues in binary, commander, docker, and source pages in Core docs - closes#569
  modules/ROOT/pages/setup/binary.adoc
  modules/ROOT/pages/setup/commander.adoc
  modules/ROOT/pages/setup/docker.adoc
  modules/ROOT/pages/setup/index.adoc
Labels: bug, core

#577 Update and fix broken links in forging page in Core docs - closes #576
  modules/ROOT/pages/management/forging.adoc
Labels: bug, core
