Repository LiskHQ/lisk-docs, pull requests merged in 2020-02, with the labels that each got.

#431 Describe network identifier - Closes #430
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/management/configuration.adoc
  modules/ROOT/pages/management/forging.adoc
  modules/ROOT/pages/management/logs.adoc
  modules/ROOT/pages/management/ssl.adoc
  modules/ROOT/pages/reference/config.adoc
Labels: status: ready

#437 Update nodejs version to 12 - Closes #356
  modules/ROOT/pages/setup/source.adoc
Labels: status: ready

#445 Update hello world - Closes #444
  modules/ROOT/pages/tutorials/hello-world.adoc
Labels: status: ready

#447 Update transport - Closes #446
  modules/ROOT/pages/tutorials/transport0.adoc
  modules/ROOT/pages/tutorials/transport1.adoc
  modules/ROOT/pages/tutorials/transport2.adoc
  modules/ROOT/pages/tutorials/transport3.adoc
Labels: status: pending review

#451 Change node version to use latest LTS - Closes #442
  modules/ROOT/pages/setup.adoc
Labels: status: ready

#455 Start transaction nonce couting from 0 - Closes #454
  modules/ROOT/pages/2-transactions.adoc
Labels: protocol

#462 Set bottom links in docs-core 2.1 - Partially closes #461
  modules/ROOT/pages/getting-started.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/management/binary.adoc
  modules/ROOT/pages/management/commander.adoc
  modules/ROOT/pages/management/docker.adoc
  modules/ROOT/pages/management/source.adoc
  modules/ROOT/pages/migration.adoc
  modules/ROOT/pages/reference/config.adoc
  modules/ROOT/pages/setup/binary.adoc
  modules/ROOT/pages/setup/commander.adoc
  modules/ROOT/pages/setup/docker.adoc
  modules/ROOT/pages/setup/source.adoc
  modules/ROOT/pages/update/binary.adoc
  modules/ROOT/pages/update/commander.adoc
  modules/ROOT/pages/update/docker.adoc
  modules/ROOT/pages/update/source.adoc
Labels: status: ready

#458 Create overview pages for sdk docs - closes #423
  modules/ROOT/pages/guides/index.adoc
  modules/ROOT/pages/reference/index.adoc
Labels: status: ready

#463 Set bottom links for core 3.0 - Partially closes #461
  modules/ROOT/pages/getting-started.adoc
  modules/ROOT/pages/management/binary.adoc
  modules/ROOT/pages/management/commander.adoc
  modules/ROOT/pages/management/docker.adoc
  modules/ROOT/pages/management/source.adoc
  modules/ROOT/pages/update/binary.adoc
  modules/ROOT/pages/update/commander.adoc
  modules/ROOT/pages/update/docker.adoc
  modules/ROOT/pages/update/source.adoc
Labels: status: ready

#465 Set bottom links for sdk 2.3 - Partially closes #461
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/reference/api.adoc
  modules/ROOT/pages/reference/lisk-framework/index.adoc
  modules/ROOT/pages/setup.adoc
  modules/ROOT/pages/tutorials/index.adoc
Labels: status: ready

#464 Set bottom links sdk 3.0- Partially closes #461
  modules/ROOT/nav.adoc
  modules/ROOT/pages/best-practices.adoc
  modules/ROOT/pages/guides/index.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/reference/index.adoc
  modules/ROOT/pages/reference/lisk-elements/index.adoc
  modules/ROOT/pages/reference/lisk-framework/index.adoc
  modules/ROOT/pages/setup.adoc
Labels: status: ready
