Repository LiskHQ/lisk-docs, pull requests merged in 2020-09, with the labels that each got.

#730 Fix transaction type - Closes #729
  modules/ROOT/pages/references/lisk-elements/transactions.adoc
Labels: sdk

#735 Align docker container name - Closes #727
  modules/ROOT/pages/tutorials/hello-world.adoc
Labels: sdk

#733 Add new page aliases - Closes #732
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/interact-with-the-api.adoc
  modules/ROOT/pages/management/application.adoc
  modules/ROOT/pages/management/commander.adoc
  modules/ROOT/pages/management/docker.adoc
  modules/ROOT/pages/management/source.adoc
  modules/ROOT/pages/reference/api-mainnet.adoc
  modules/ROOT/pages/reference/config.adoc
  modules/ROOT/pages/setup/application.adoc
  modules/ROOT/pages/update/application.adoc
Labels: core

#746 Add version to lisk-sdk snippets - Closes #739
  modules/ROOT/pages/getting-started.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/setup.adoc
  modules/ROOT/pages/tutorials/cashback.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
Labels: sdk

#697 Overall review of SDK docs 3.0.2 - Closes #686
  modules/ROOT/pages/guides/app-development/broadcast.adoc
  modules/ROOT/pages/guides/app-development/configuration.adoc
  modules/ROOT/pages/guides/app-development/custom-transactions.adoc
  modules/ROOT/pages/guides/app-development/frontend.adoc
  modules/ROOT/pages/guides/app-development/launch.adoc
  modules/ROOT/pages/guides/app-development/test-transaction.adoc
  modules/ROOT/pages/guides/index.adoc
  modules/ROOT/pages/guides/node-management/enable-ssl.adoc
  modules/ROOT/pages/guides/node-management/forging.adoc
  modules/ROOT/pages/guides/node-management/logging.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/references/api-specification.adoc
  modules/ROOT/pages/references/changelog.adoc
  modules/ROOT/pages/references/config.adoc
  modules/ROOT/pages/references/index.adoc
  modules/ROOT/pages/references/lisk-commander/commands.adoc
  modules/ROOT/pages/references/lisk-commander/index.adoc
  modules/ROOT/pages/references/lisk-commander/lisk-core-commands.adoc
  modules/ROOT/pages/references/lisk-commander/sensitive-inputs.adoc
  modules/ROOT/pages/references/lisk-elements/api-client.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/node.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/transactions.adoc
  modules/ROOT/pages/references/lisk-elements/constants.adoc
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
  modules/ROOT/pages/references/lisk-elements/index.adoc
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
  modules/ROOT/pages/references/lisk-elements/passphrase.adoc
  modules/ROOT/pages/references/lisk-elements/transactions.adoc
  modules/ROOT/pages/references/lisk-framework/index.adoc
  modules/ROOT/pages/setup.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/pages/tutorials/index.adoc
  modules/ROOT/pages/tutorials/supply-chain/index.adoc
  modules/ROOT/pages/tutorials/supply-chain/part1.adoc
  modules/ROOT/pages/tutorials/supply-chain/part2.adoc
  modules/ROOT/pages/tutorials/supply-chain/part3.adoc
  modules/ROOT/pages/tutorials/supply-chain/part4.adoc
  modules/ROOT/partials/config-object.adoc
  modules/ROOT/partials/install-node.adoc
  modules/ROOT/partials/install-postgres.adoc
Labels: bug, sdk
