Repository LiskHQ/lisk-docs, pull requests merged in 2020-11, with the labels that each got.

#785 Mention hash onion in forging guide - Closes #784
  modules/ROOT/pages/guides/node-management/forging.adoc
Labels: component: sdk

#753 Revisit page meta descriptions in Core docs - Closes #738
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/interact-with-the-api.adoc
  modules/ROOT/pages/management/application.adoc
  modules/ROOT/pages/management/commander.adoc
  modules/ROOT/pages/management/configuration.adoc
  modules/ROOT/pages/management/docker.adoc
  modules/ROOT/pages/management/forging.adoc
  modules/ROOT/pages/management/index.adoc
  modules/ROOT/pages/management/source.adoc
  modules/ROOT/pages/migration.adoc
  modules/ROOT/pages/reference/api-mainnet.adoc
  modules/ROOT/pages/reference/api.adoc
  modules/ROOT/pages/reference/config.adoc
  modules/ROOT/pages/setup/application.adoc
  modules/ROOT/pages/setup/commander.adoc
  modules/ROOT/pages/setup/docker.adoc
  modules/ROOT/pages/setup/index.adoc
  modules/ROOT/pages/setup/source.adoc
  modules/ROOT/pages/update/application.adoc
  modules/ROOT/pages/update/commander.adoc
  modules/ROOT/pages/update/docker.adoc
  modules/ROOT/pages/update/index.adoc
  modules/ROOT/pages/update/source.adoc
Labels: component: core, component: sdk, type: bug

#787 Add account mgmt guide - Closes #783
  modules/ROOT/nav.adoc
  modules/ROOT/pages/guides/node-management/managing-accounts.adoc
Labels: component: sdk

#781 Revisit meta descriptions in SDK docs 3.0.2 - Closes #780
  modules/ROOT/pages/guides/app-development/broadcast.adoc
  modules/ROOT/pages/guides/app-development/configuration.adoc
  modules/ROOT/pages/guides/app-development/custom-transactions.adoc
  modules/ROOT/pages/guides/app-development/frontend.adoc
  modules/ROOT/pages/guides/app-development/interact-with-api.adoc
  modules/ROOT/pages/guides/app-development/launch.adoc
  modules/ROOT/pages/guides/app-development/test-transaction.adoc
  modules/ROOT/pages/guides/index.adoc
  modules/ROOT/pages/guides/node-management/api-access.adoc
  modules/ROOT/pages/guides/node-management/enable-ssl.adoc
  modules/ROOT/pages/guides/node-management/forging.adoc
  modules/ROOT/pages/guides/node-management/logging.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/references/api-specification.adoc
  modules/ROOT/pages/references/changelog.adoc
  modules/ROOT/pages/references/config.adoc
  modules/ROOT/pages/references/index.adoc
  modules/ROOT/pages/references/lisk-commander/commands.adoc
  modules/ROOT/pages/references/lisk-commander/index.adoc
  modules/ROOT/pages/references/lisk-commander/lisk-core-commands.adoc
  modules/ROOT/pages/references/lisk-commander/sensitive-inputs.adoc
  modules/ROOT/pages/references/lisk-elements/api-client.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/accounts.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/blocks.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/dapps.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/delegates.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/node.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/peers.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/signatures.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/transactions.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/voters.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/votes.adoc
  modules/ROOT/pages/references/lisk-elements/client.adoc
  modules/ROOT/pages/references/lisk-elements/constants.adoc
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
  modules/ROOT/pages/references/lisk-elements/index.adoc
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
  modules/ROOT/pages/references/lisk-elements/passphrase.adoc
  modules/ROOT/pages/references/lisk-elements/transaction-pool.adoc
  modules/ROOT/pages/references/lisk-elements/transactions.adoc
  modules/ROOT/pages/references/lisk-elements/validator.adoc
  modules/ROOT/pages/references/lisk-framework/index.adoc
  modules/ROOT/pages/setup.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/pages/tutorials/index.adoc
  modules/ROOT/pages/tutorials/supply-chain/index.adoc
  modules/ROOT/pages/tutorials/supply-chain/part1.adoc
  modules/ROOT/pages/tutorials/supply-chain/part2.adoc
  modules/ROOT/pages/tutorials/supply-chain/part3.adoc
  modules/ROOT/pages/tutorials/supply-chain/part4.adoc
Labels: component: sdk, type: update

#777 Update Lisk framework docs - Closes #769
  modules/ROOT/assets/images/architecture-3-level.png
  modules/ROOT/assets/images/architecture.png
  modules/ROOT/assets/images/communication-architecture.png
  modules/ROOT/assets/images/diagram_framework.png
  modules/ROOT/assets/images/off-chain-architecture.png
  modules/ROOT/assets/images/on-chain-architecture.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/explanations/architecture/communication-architecture.adoc
  modules/ROOT/pages/explanations/architecture/index.adoc
  modules/ROOT/pages/explanations/architecture/off-chain-architecture.adoc
  modules/ROOT/pages/explanations/architecture/on-chain-architecture.adoc
  modules/ROOT/pages/explanations/consensus.adoc
  modules/ROOT/pages/explanations/framework.adoc
  modules/ROOT/pages/explanations/modules.adoc
  modules/ROOT/pages/explanations/plugins.adoc
  modules/ROOT/pages/references/config.adoc
  modules/ROOT/pages/references/lisk-framework/index.adoc
Labels: component: sdk

#790 Update Lisk Elements packages reference - Closes #770
  modules/ROOT/assets/images/p2p.png
  modules/ROOT/assets/images/peers.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/references/lisk-elements/api-client.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/accounts.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/blocks.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/dapps.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/delegates.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/node.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/peers.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/transactions.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/voters.adoc
  modules/ROOT/pages/references/lisk-elements/api-client/votes.adoc
  modules/ROOT/pages/references/lisk-elements/chain.adoc
  modules/ROOT/pages/references/lisk-elements/client.adoc
  modules/ROOT/pages/references/lisk-elements/codec.adoc
  modules/ROOT/pages/references/lisk-elements/constants.adoc
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
  modules/ROOT/pages/references/lisk-elements/db.adoc
  modules/ROOT/pages/references/lisk-elements/dpos.adoc
  modules/ROOT/pages/references/lisk-elements/genesis.adoc
  modules/ROOT/pages/references/lisk-elements/index.adoc
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
  modules/ROOT/pages/references/lisk-elements/passphrase.adoc
  modules/ROOT/pages/references/lisk-elements/transaction-pool.adoc
  modules/ROOT/pages/references/lisk-elements/transactions.adoc
  modules/ROOT/pages/references/lisk-elements/tree.adoc
  modules/ROOT/pages/references/lisk-elements/utils.adoc
  modules/ROOT/pages/references/lisk-elements/validator.adoc
Labels: component: sdk

#788 Update API spec to v5 - Closes #772
  modules/ROOT/pages/references/api-specification.adoc
Labels: component: sdk

#792 Update Lisk Commander reference - Closes #771
  modules/ROOT/nav.adoc
  modules/ROOT/pages/references/lisk-commander/commands.adoc
  modules/ROOT/pages/references/lisk-commander/index.adoc
  modules/ROOT/pages/references/lisk-commander/lisk-core-commands.adoc
Labels: component: sdk

#795 Fix shuffling typo
  modules/ROOT/pages/consensus-algorithm.adoc
Labels: component: protocol, type: bug

#803 Update Hello World tutorial - Closes #797
  modules/ROOT/assets/images/tutorials/account-details.png
  modules/ROOT/assets/images/tutorials/create-account.png
  modules/ROOT/assets/images/tutorials/faucet.png
  modules/ROOT/assets/images/tutorials/hello-counter.png
  modules/ROOT/assets/images/tutorials/home.png
  modules/ROOT/assets/images/tutorials/send-hello.png
  modules/ROOT/assets/images/tutorials/transfer.png
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/pages/tutorials/index.adoc
Labels: component: sdk
