Repository LiskHQ/lisk-docs, pull requests merged in 2021-02, with the labels that each got.

#958 Update configuration reference - Closes #947
  modules/ROOT/pages/references/configuration.adoc
Labels: component: service

#955 Add page about the subscribe API - Closes #949
  modules/ROOT/pages/references/subscribe-api.adoc
Labels: component: service

#939 Update cryptography reference - Closes #934
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
Labels: component: sdk

#957 Add guide how to protect a non forging node - Closes #843
  modules/ROOT/nav.adoc
  modules/ROOT/pages/guides/node-management/non-forging-node-protection.adoc
Labels: component: sdk

#953 Remove setup instructions regarding postgresql - Closes #944
  modules/ROOT/pages/setup/source.adoc
Labels: component: service

#954 Add RPC API reference - Closes #948
  modules/ROOT/nav.adoc
  modules/ROOT/pages/references/rpc-api.adoc
Labels: component: service

#961 Update PM2 configuration - Closes #946
  modules/ROOT/pages/configuration/source.adoc
Labels: component: service

#966 Bump version to 0.2.0 - Closes #964
  antora.yml
Labels: component: service

#975 Adding prerequisites to config guide in configuration in SDK docs v5 - Closes #967
  modules/ROOT/pages/guides/app-development/configuration.adoc
Labels: component: sdk, type: update

#970 Outdated example for peers in Lisk core docs v3.0.0 beta.4 - closes #929
  modules/ROOT/pages/reference/api.adoc
Labels: component: core, type: bug

#960 Update docker configuration - Closes #945
  modules/ROOT/pages/configuration/docker.adoc
Labels: component: service

#978 Update code examples in asset guide - Closes #972
  modules/ROOT/pages/guides/app-development/asset.adoc
Labels: component: sdk

#979 Update code examples in the plugin guide - Closes #973
  modules/ROOT/pages/guides/app-development/plugin.adoc
Labels: component: sdk

#977 Add MYSQL to Lisk Service docs - Closes #976
  modules/ROOT/pages/references/configuration.adoc
  modules/ROOT/pages/setup/source.adoc
Labels: component: service

#981 Update link to hello world code repository - Closes #980
  modules/ROOT/pages/architecture/communication-architecture.adoc
  modules/ROOT/pages/architecture/off-chain-architecture.adoc
  modules/ROOT/pages/architecture/on-chain-architecture.adoc
  modules/ROOT/pages/rpc-endpoints.adoc
  modules/ROOT/pages/tutorials/hello-world.adoc
  modules/ROOT/pages/tutorials/supply-chain/index.adoc
  modules/ROOT/pages/tutorials/supply-chain/part1.adoc
  modules/ROOT/pages/tutorials/supply-chain/part2.adoc
  modules/ROOT/pages/tutorials/supply-chain/part3.adoc
  modules/ROOT/pages/tutorials/supply-chain/part4.adoc
Labels: component: sdk

#974 Update GTM script and add Cookiebot - Closes #969
  src/partials/header-scripts.hbs
Labels: component: ui

#983 Updated broken links in enabling forging in Core docs v3 beta-4 - Closes #928
  modules/ROOT/pages/management/forging.adoc
Labels: component: core, type: bug

#985 Minor updates in enabling forging in Core docs v3 beta-4 - Closes #984
  modules/ROOT/pages/management/forging.adoc
Labels: component: core, type: bug

#999 Fix broken link in Core v2.1.6 - Closes #998
  modules/ROOT/pages/setup/commander.adoc
Labels: component: core, type: bug

#1002 Fix broken link in Lisk Service docs - Closes #1001
  modules/ROOT/pages/index.adoc
Labels: component: service, type: bug

#1008 Add max length for data - Closes #904
  modules/protocol/pages/transactions.adoc
Labels: component: sdk
