Repository LiskHQ/lisk-docs, pull requests merged in 2021-11, with the labels that each got.

#1231 Update diagram, remove links - Closes #1229
  modules/ROOT/assets/images/architecture.png
  modules/ROOT/pages/index.adoc
Labels: component: service

#1226 Add faucet guide - Closes #1153
  modules/ROOT/nav.adoc
  modules/ROOT/pages/guides/app-development/faucet.adoc
Labels: component: sdk

#1228 Updates and all associated links in the glossary in sdk docs v5.1.4 - Closes #1189
  modules/ROOT/pages/advanced-explanations/architecture.adoc
  modules/ROOT/pages/advanced-explanations/communication.adoc
  modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
  modules/ROOT/pages/advanced-explanations/schemas.adoc
  modules/ROOT/pages/glossary.adoc
  modules/ROOT/pages/guides/app-development/asset.adoc
  modules/ROOT/pages/guides/app-development/configuration.adoc
  modules/ROOT/pages/guides/app-development/frontend.adoc
  modules/ROOT/pages/guides/app-development/launch.adoc
  modules/ROOT/pages/guides/app-development/setup.adoc
  modules/ROOT/pages/guides/app-development/testing.adoc
  modules/ROOT/pages/guides/node-management/forging-node-protection.adoc
  modules/ROOT/pages/guides/node-management/forging.adoc
  modules/ROOT/pages/guides/node-management/logging.adoc
  modules/ROOT/pages/guides/node-management/non-forging-node-protection.adoc
  modules/ROOT/pages/guides/node-management/signing-transactions-offline.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/introduction/blockchain-applications.adoc
  modules/ROOT/pages/introduction/modules.adoc
  modules/ROOT/pages/references/application-cli.adoc
  modules/ROOT/pages/references/lisk-commander/commands.adoc
  modules/ROOT/pages/references/lisk-commander/index.adoc
  modules/ROOT/pages/references/lisk-elements/codec.adoc
  modules/ROOT/pages/references/lisk-elements/index.adoc
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
  modules/ROOT/pages/references/lisk-elements/validator.adoc
  modules/ROOT/pages/references/lisk-framework/dashboard-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/dpos-module.adoc
  modules/ROOT/pages/references/lisk-framework/http-api-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/report-misbehavior-plugin.adoc
  modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
  modules/ROOT/pages/tutorials/lns/3-cli.adoc
  modules/ROOT/pages/tutorials/lns/index.adoc
  modules/ROOT/pages/tutorials/nft.adoc
  modules/ROOT/pages/tutorials/srs.adoc
  modules/ROOT/partials/install-node.adoc
  modules/protocol/pages/accounts.adoc
  modules/protocol/pages/appendix.adoc
  modules/protocol/pages/blocks.adoc
  modules/protocol/pages/consensus-algorithm.adoc
  modules/protocol/pages/index.adoc
  modules/protocol/pages/transactions.adoc
Labels: component: sdk, type: update

#1230 Fixes broken links in sdk docs v5.2.0 - Closes #1220
  modules/ROOT/pages/tutorials/lns/4-tests.adoc
  modules/protocol/pages/index.adoc
Labels: component: sdk, type: update

#1268 Fixes broken links in Core docs v2 - Closes #1232
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/management/commander.adoc
  modules/ROOT/pages/setup/application.adoc
  modules/ROOT/pages/setup/commander.adoc
  modules/ROOT/pages/setup/docker.adoc
  modules/ROOT/pages/setup/source.adoc
  modules/ROOT/pages/update/application.adoc
  modules/ROOT/pages/update/commander.adoc
  modules/ROOT/pages/update/docker.adoc
  modules/ROOT/pages/update/source.adoc
Labels: component: core, type: update

#1283 Fixes broken links in SDK docs v3.0.2 - Closes #1282
  modules/ROOT/pages/references/lisk-elements/index.adoc
Labels: component: sdk, type: update

#1291 Add getPublicKey & getRandomBytes references - Closes #1285
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
Labels: component: sdk

#1300 Improve Docker setup guide - Closes #1275
  modules/ROOT/pages/setup/docker.adoc
Labels: component: service

#1305 Update guides and config reference - Closes #1278
  modules/ROOT/pages/configuration/docker.adoc
  modules/ROOT/pages/configuration/source.adoc
  modules/ROOT/pages/management/docker.adoc
  modules/ROOT/pages/management/source.adoc
  modules/ROOT/pages/references/configuration.adoc
Labels: component: service
