Repository LiskHQ/lisk-docs, pull requests merged in 2021-05, with the labels that each got.

#1037 Create migration guide - Closes #1025
  modules/ROOT/nav.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/management/forging.adoc
  modules/ROOT/pages/management/migration.adoc
  modules/ROOT/pages/management/pm2.adoc
  modules/ROOT/pages/migration.adoc
Labels: component: core

#1069 Update lisk-genesis reference - Closes #1067
  modules/ROOT/pages/references/lisk-elements/genesis.adoc
Labels: component: sdk

#1081 Fixes broken link in What is Lisk Core page in Core docs v3-beta-5 - Closes #1057
  modules/ROOT/pages/index.adoc
Labels: component: core, type: bug

#1088 Fixes minor error in Managing Accounts in Core docs v3 beta-6 - Closes #1087
  modules/ROOT/pages/management/account-management.adoc
Labels: component: core, type: bug

#1091 Fix SRS tutorial - Closes #1089
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/tutorials/srs.adoc
Labels: component: sdk

#1096 Update Commander reference - Closes #1073
  modules/ROOT/pages/references/lisk-commander/commands.adoc
  modules/ROOT/pages/references/lisk-commander/index.adoc
Labels: component: sdk

#1090 Add custom DPoS config options - Closes #1086
  modules/ROOT/pages/architecture/index.adoc
  modules/ROOT/pages/dpos-module.adoc
  modules/ROOT/pages/guides/app-development/configuration.adoc
  modules/ROOT/pages/references/lisk-framework/forger-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/http-api-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/report-misbehavior-plugin.adoc
Labels: component: sdk
