Repository LiskHQ/lisk-docs, pull requests merged in 2021-03, with the labels that each got.

#994 Removed outdated pages to fix broken links in Core v3.0.0 beta-4 - Closes #993
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/update/application.adoc
  modules/ROOT/pages/update/commander.adoc
  modules/ROOT/pages/update/docker.adoc
  modules/ROOT/pages/update/source.adoc
Labels: component: core, type: bug

#1013 Fixes minor errors in transaction pool page in SDK docs v5 - Closes #1012
  modules/ROOT/pages/references/lisk-elements/transaction-pool.adoc
Labels: component: sdk, type: bug

#1015 Fixes minor errors in forging-node-protection in SDK docs v5 - Closes #1014
  modules/ROOT/pages/guides/node-management/forging-node-protection.adoc
Labels: component: sdk, type: bug

#1017 Update readme file in SDK docs v5 - Closes #913
  README.adoc
Labels: component: sdk, type: update

#1020 Removed caret in commands in SDK docs v5 - Closes #1018
  modules/ROOT/pages/references/lisk-commander/commands.adoc
Labels: component: sdk, type: bug

#1021 Fixed broken link and removed caret in P2P in SDK docs v5 - Closes #1019
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
Labels: component: sdk, type: bug

#1024 Fixes minor correction in report-misbehavior-plugin in SDK docs v5 - Closes #1023
  modules/ROOT/pages/references/lisk-framework/report-misbehavior-plugin.adoc
Labels: component: sdk, type: bug

#1029 Fixes examples references and links in P2P in SDK docs v5 - Closes #1028
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
Labels: component: sdk, type: bug

#982 Add NFT tutorial - Closes #844
  modules/ROOT/assets/images/tutorials/nft/01-home-notes.png
  modules/ROOT/assets/images/tutorials/nft/01-home.png
  modules/ROOT/assets/images/tutorials/nft/02-create-account.png
  modules/ROOT/assets/images/tutorials/nft/03-transfer-funds.png
  modules/ROOT/assets/images/tutorials/nft/04-create-nft.png
  modules/ROOT/assets/images/tutorials/nft/05-home-nft.png
  modules/ROOT/assets/images/tutorials/nft/06-transfer-nft.png
  modules/ROOT/assets/images/tutorials/nft/07-home-nft.png
  modules/ROOT/assets/images/tutorials/nft/08-purchase-nft.png
  modules/ROOT/assets/images/tutorials/nft/09-collector2-account-page.png
  modules/ROOT/assets/images/tutorials/nft/10-collector1-account-page.png
  modules/ROOT/assets/images/tutorials/nft/11-transactions.png
  modules/ROOT/assets/images/tutorials/nft/12-create-mew.png
  modules/ROOT/assets/images/tutorials/nft/13-home-nft.png
  modules/ROOT/assets/images/tutorials/nft/nft-overview.png
  modules/ROOT/assets/images/tutorials/nft/nft.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/architecture/index.adoc
  modules/ROOT/pages/dpos-module.adoc
  modules/ROOT/pages/keys-module.adoc
  modules/ROOT/pages/sequence-module.adoc
  modules/ROOT/pages/token-module.adoc
  modules/ROOT/pages/tutorials/index.adoc
  modules/ROOT/pages/tutorials/nft.adoc
Labels: component: sdk

#1032 Fixes minor errors in setup page in SDK docs v5 - Closes #1030
  modules/ROOT/pages/guides/app-development/setup.adoc
Labels: component: sdk, type: bug

#1033 Fixes minor errors in forging node in SDK docs v5 - Closes #1011
  modules/ROOT/pages/guides/node-management/forging.adoc
Labels: component: sdk, type: bug

#1034 Fixes minor errors in framework index in SDK docs v5 - Closes #1022
  modules/ROOT/pages/references/lisk-framework/index.adoc
Labels: component: sdk, type: bug

#1036 Update address terminology - Closes #1031
  modules/ROOT/assets/images/architecture.png
  modules/ROOT/assets/images/communication-architecture.png
  modules/ROOT/pages/architecture/communication-architecture.adoc
  modules/ROOT/pages/architecture/index.adoc
  modules/ROOT/pages/architecture/off-chain-architecture.adoc
  modules/ROOT/pages/architecture/on-chain-architecture.adoc
  modules/ROOT/pages/guides/app-development/setup.adoc
  modules/ROOT/pages/guides/node-management/forging.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/quickstart.adoc
  modules/ROOT/pages/references/lisk-commander/commands.adoc
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
  modules/ROOT/pages/rpc-endpoints.adoc
  modules/ROOT/pages/tutorials/nft.adoc
Labels: component: sdk

#1010 Create SRS tutorial - Closes #1007
  modules/ROOT/assets/images/tutorials/srs/01-home.png
  modules/ROOT/assets/images/tutorials/srs/02-setup.png
  modules/ROOT/assets/images/tutorials/srs/02-setup2.png
  modules/ROOT/assets/images/tutorials/srs/03-logs.png
  modules/ROOT/assets/images/tutorials/srs/04-account-details-1vouch.png
  modules/ROOT/assets/images/tutorials/srs/04-account-details-2vouch.png
  modules/ROOT/assets/images/tutorials/srs/04-vouch.png
  modules/ROOT/assets/images/tutorials/srs/04-vouch2.png
  modules/ROOT/assets/images/tutorials/srs/04-vouch3.png
  modules/ROOT/assets/images/tutorials/srs/05-initiate.png
  modules/ROOT/assets/images/tutorials/srs/05-initiate2.png
  modules/ROOT/assets/images/tutorials/srs/06-account-details.png
  modules/ROOT/assets/images/tutorials/srs/07-node-info.png
  modules/ROOT/assets/images/tutorials/srs/08-claim.png
  modules/ROOT/assets/images/tutorials/srs/08-claim2.png
  modules/ROOT/assets/images/tutorials/srs/09-account-original.png
  modules/ROOT/assets/images/tutorials/srs/09-account-rescuer.png
  modules/ROOT/assets/images/tutorials/srs/Screen Shot 2021-03-12 at 14.28.34.png
  modules/ROOT/assets/images/tutorials/srs/account-details-start.png
  modules/ROOT/assets/images/tutorials/srs/no-recoverable-accounts.png
  modules/ROOT/assets/images/tutorials/srs/srs-overview.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/tutorials/index.adoc
  modules/ROOT/pages/tutorials/srs.adoc
Labels: component: sdk

#952 Build Glossary and Abbreviations page in References in SDK docs 5.0.3 - Closes #897
  modules/ROOT/nav.adoc
  modules/ROOT/pages/dpos-module.adoc
  modules/ROOT/pages/guides/node-management/forging-node-protection.adoc
  modules/ROOT/pages/guides/node-management/non-forging-node-protection.adoc
  modules/ROOT/pages/references/glossary.adoc
  modules/ROOT/pages/references/lisk-commander/commands.adoc
  modules/ROOT/pages/references/lisk-commander/index.adoc
  modules/ROOT/pages/references/lisk-elements/chain.adoc
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
  modules/ROOT/pages/references/lisk-elements/index.adoc
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
  modules/ROOT/pages/references/lisk-elements/validator.adoc
  modules/ROOT/pages/references/lisk-framework/http-api-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
Labels: component: sdk
