Repository LiskHQ/lisk-docs, pull requests merged in 2021-12, with the labels that each got.

#1301 Add public WebSocket APIs to index page - Closes #1277
  modules/ROOT/pages/index.adoc
Labels: component: service

#1311 Add sections how to reset the mysql db - Closes #1270
  modules/ROOT/pages/management/docker.adoc
  modules/ROOT/pages/management/source.adoc
Labels: component: service

#1309 Add guide how to post transactions - Closes #1272
  modules/ROOT/nav.adoc
  modules/ROOT/pages/management/post-transactions.adoc
Labels: component: service

#1310 Fixes broken links in Lisk Service v0.5.0 - Closes #1302
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/references/subscribe-api.adoc
Labels: type: bug, component: service

#1313 Fixes broken link in SDK docs v3.0.2 - Closes #1312
  modules/ROOT/pages/references/lisk-elements/index.adoc
Labels: type: bug, component: sdk

#1318 How to calculate the min fee of a tx - Closes #1255
  modules/ROOT/nav.adoc
  modules/ROOT/pages/guides/app-development/min-fee.adoc
Labels: component: sdk

#1317 RPC config updates - Closes #1287
  modules/ROOT/pages/advanced-explanations/communication.adoc
  modules/ROOT/pages/guides/app-development/configuration.adoc
  modules/ROOT/pages/references/config.adoc
Labels: component: sdk

#1320 Improve schema explanations - Closes #1236
  modules/ROOT/pages/advanced-explanations/schemas.adoc
  modules/ROOT/pages/guides/app-development/asset.adoc
  modules/ROOT/pages/introduction/modules.adoc
  modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
Labels: component: sdk

#1322 Add RPC example outputs - Closes #870
  modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
Labels: component: sdk
