Repository LiskHQ/lisk-docs, pull requests merged in 2021-04, with the labels that each got.

#1041 Update wording related to addresses
  modules/protocol/pages/appendix.adoc
Labels: component: sdk, type: bug

#1047 Fix fixedPeers example - Closes #1042
  modules/ROOT/pages/guides/node-management/forging-node-protection.adoc
Labels: component: sdk

#1045 Fix issues in mgmt guides - Closes #1044
  modules/ROOT/pages/management/configuration.adoc
  modules/ROOT/pages/management/forging.adoc
Labels: component: core

#1053 Change payload size limit unit from "kB" to "KiB"
  modules/protocol/pages/blocks.adoc
Labels: component: sdk, type: bug

#1048 Add legacy account module reference page - Closes #1046
  modules/ROOT/nav.adoc
  modules/ROOT/pages/reference/legacy-account-module.adoc
Labels: component: core

#1055 Fixes broken link in account management in Core docs v3-beta-5 - Closes #1052
  modules/ROOT/pages/management/account-management.adoc
Labels: component: core, type: bug

#1061 Update in glossary in SDK docs v5 - Closes #1060
  modules/ROOT/pages/references/glossary.adoc
Labels: component: sdk, type: bug

#1058 Fixes minor error in configuration in Core docs v3-beta-5 - Closes #1056
  modules/ROOT/pages/management/configuration.adoc
Labels: component: core, type: bug

#1062 Fix issues in NFT tutorial - Closes #1059
  modules/ROOT/pages/tutorials/nft.adoc
Labels: component: sdk

#1066 Update mergeDeep reference - Closes #1065
  modules/ROOT/pages/references/lisk-elements/utils.adoc
Labels: component: sdk
