Repository LiskHQ/lisk-docs, pull requests merged in 2021-06, with the labels that each got.

#1094 Add page about the dashboard plugin - Closes #1071
  modules/ROOT/nav.adoc
  modules/ROOT/pages/references/lisk-framework/dashboard-plugin.adoc
Labels: component: sdk

#1103 Update the quickstart guide - Closes #1101
  modules/ROOT/pages/guides/app-development/setup.adoc
  modules/ROOT/pages/quickstart.adoc
Labels: component: sdk

#1109 Add tip how to reset the db to setup guide - Closes #1099
  modules/ROOT/pages/guides/app-development/setup.adoc
Labels: component: sdk

#1107 Update plugin guide - Closes #1105
  modules/ROOT/pages/guides/app-development/plugin.adoc
Labels: component: sdk

#1102 Update the module guide - Closes #1076
  modules/ROOT/pages/guides/app-development/module.adoc
Labels: component: sdk

#1106 Update asset guide - Closes #1104
  modules/ROOT/pages/guides/app-development/asset.adoc
Labels: component: sdk

#1116 Update migration guide - Closes #1112
  modules/ROOT/pages/management/migration.adoc
Labels: component: core

#1118 Glossary updates in SDK docs v5 - Closes #1117
  modules/ROOT/pages/references/glossary.adoc
Labels: component: sdk, type: update

#1111 List supported platforms in SDK docs v5 -Closes #1108
  modules/ROOT/pages/guides/app-development/setup.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/quickstart.adoc
Labels: component: sdk, type: update

#1122 Fixes broken link in Core docs v3 beta-6 - Closes #1121
  modules/ROOT/pages/index.adoc
Labels: component: core, type: bug

#1124 Fixes broken link in index page in SDK docs v4 - Closes #1123
  modules/ROOT/pages/index.adoc
Labels: component: sdk, type: update

#1128 Fixes broken link in Core docs v2.1.6 - Closes #1127
  modules/ROOT/pages/setup/docker.adoc
Labels: component: core, type: update

#1133 Update subscribe API reference - Closes #1132
  modules/ROOT/pages/references/subscribe-api.adoc
Labels: component: service

#1135 Update config reference - Closes #1134
  modules/ROOT/pages/references/configuration.adoc
Labels: component: service

#1130 Fix broken link in Lisk Service docs - Closes #1129
  modules/ROOT/pages/setup/source.adoc
Labels: component: service, type: update
