Repository LiskHQ/lisk-docs, pull requests merged in 2022-01, with the labels that each got.

#1328 Fix links and update footnotes SDKv5 - Partially closes #1323
  modules/ROOT/pages/glossary.adoc
  modules/ROOT/pages/guides/app-development/dashboard.adoc
  modules/ROOT/pages/introduction/blockchain-applications.adoc
  modules/ROOT/pages/introduction/modules.adoc
  modules/protocol/pages/consensus-algorithm.adoc
Labels: component: sdk

#1324 Fix links Core v2 - Partially closes #1323
  modules/ROOT/pages/update/application.adoc
Labels: component: core

#1331 replace dashboard with faucet plugin name
  modules/ROOT/pages/guides/app-development/launch.adoc
Labels: component: sdk

#1330 Restructure guide "singing txs offline" - Closes #1315
  modules/ROOT/pages/guides/app-development/decoding-transactions-blocks.adoc
  modules/ROOT/pages/guides/node-management/signing-transactions-offline.adoc
Labels: component: sdk

#1306 Update on glossary and abbreviations in SDK docs - Closes #1284
  modules/ROOT/pages/glossary.adoc
  modules/ROOT/pages/introduction/modules.adoc
  modules/ROOT/pages/references/lisk-framework/dpos-module.adoc
  modules/ROOT/pages/references/lisk-framework/http-api-plugin.adoc
  modules/protocol/pages/accounts.adoc
  modules/protocol/pages/consensus-algorithm.adoc
  modules/protocol/pages/transactions.adoc
Labels: component: sdk, type: update

#1367 Update to Core version 3.0.3 - Closes #1365
  antora.yml
  modules/ROOT/pages/reference/cli.adoc
  modules/ROOT/pages/setup/binary.adoc
  modules/ROOT/pages/setup/docker.adoc
  modules/ROOT/pages/setup/source.adoc
  modules/ROOT/pages/update/binary.adoc
  modules/ROOT/pages/update/docker.adoc
  modules/ROOT/pages/update/npm.adoc
  modules/ROOT/pages/update/source.adoc
Labels: component: core

#1374 Update variables names - Closes #1373
  modules/ROOT/pages/guides/app-development/decoding-transactions-blocks.adoc
Labels: component: sdk
