Repository LiskHQ/lisk-docs, pull requests merged in 2022-02, with the labels that each got.

#1378 Update toolbar and navigation - Closes #1352, #1353, #1358
  docs/modules/ROOT/nav.adoc
  ui/src/css/extensions/common-custom.css
  ui/src/css/extensions/custom-dark-vars.css
  ui/src/css/extensions/custom-dark.css
  ui/src/css/extensions/custom-vars.css
  ui/src/css/extensions/custom.css
  ui/src/css/extensions/page-components.css
  ui/src/img/chevron-left.svg
  ui/src/img/collapse-icon-filled.svg
  ui/src/img/collapse-icon-outlined.svg
  ui/src/img/home-filled.svg
  ui/src/img/home-outlined.svg
  ui/src/img/moon-filled.svg
  ui/src/img/pencil-filled.svg
  ui/src/img/pencil.svg
  ui/src/js/vendor/custom.js
  ui/src/js/vendor/docsearch.min.js
  ui/src/partials/footer-scripts.hbs
  ui/src/partials/head-styles.hbs
  ui/src/partials/header-content.hbs
  ui/src/partials/toolbar.hbs
Labels: component: ui

#1388 Update table style - Closes #1363
  ui/src/css/extensions/common-custom.css
Labels: component: ui

#1394 Update dependencies - Closes #1389
  modules/ROOT/pages/setup/binary.adoc
  modules/ROOT/pages/setup/npm.adoc
  modules/ROOT/pages/setup/snap.adoc
  modules/ROOT/pages/setup/source.adoc
Labels: component: core

#1395 Overall review of SDK docs v5 - Closes #1035
  modules/ROOT/assets/images/guides/launch/devnet-node.png
  modules/ROOT/assets/images/guides/launch/testnet-delegate-nodes.png
  modules/ROOT/assets/images/guides/launch/testnet-node.png
  modules/ROOT/pages/advanced-explanations/architecture.adoc
  modules/ROOT/pages/advanced-explanations/communication.adoc
  modules/ROOT/pages/guides/app-development/asset.adoc
  modules/ROOT/pages/guides/app-development/dashboard.adoc
  modules/ROOT/pages/guides/app-development/faucet.adoc
  modules/ROOT/pages/guides/app-development/frontend.adoc
  modules/ROOT/pages/guides/app-development/genesis-block.adoc
  modules/ROOT/pages/guides/app-development/launch.adoc
  modules/ROOT/pages/guides/app-development/module.adoc
  modules/ROOT/pages/guides/app-development/plugin.adoc
  modules/ROOT/pages/guides/app-development/setup.adoc
  modules/ROOT/pages/guides/app-development/testing.adoc
  modules/ROOT/pages/guides/node-management/forging-node-protection.adoc
  modules/ROOT/pages/guides/node-management/forging.adoc
  modules/ROOT/pages/guides/node-management/logging.adoc
  modules/ROOT/pages/guides/node-management/non-forging-node-protection.adoc
  modules/ROOT/pages/guides/node-management/signing-transactions-offline.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/introduction/blockchain-applications.adoc
  modules/ROOT/pages/introduction/modules.adoc
  modules/ROOT/pages/introduction/plugins.adoc
  modules/ROOT/pages/references/application-cli.adoc
  modules/ROOT/pages/references/lisk-commander/commands.adoc
  modules/ROOT/pages/references/lisk-commander/index.adoc
  modules/ROOT/pages/references/lisk-elements/chain.adoc
  modules/ROOT/pages/references/lisk-elements/codec.adoc
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
  modules/ROOT/pages/references/lisk-elements/genesis.adoc
  modules/ROOT/pages/references/lisk-elements/index.adoc
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
  modules/ROOT/pages/references/lisk-elements/transaction-pool.adoc
  modules/ROOT/pages/references/lisk-elements/transactions.adoc
  modules/ROOT/pages/references/lisk-elements/utils.adoc
  modules/ROOT/pages/references/lisk-elements/validator.adoc
  modules/ROOT/pages/references/lisk-framework/dpos-module.adoc
  modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/forger-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/http-api-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/index.adoc
  modules/ROOT/pages/references/lisk-framework/keys-module.adoc
  modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/report-misbehavior-plugin.adoc
  modules/ROOT/pages/references/lisk-framework/test-suite.adoc
  modules/ROOT/pages/references/lisk-framework/token-module.adoc
  modules/ROOT/pages/tutorials/index.adoc
  modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
  modules/ROOT/pages/tutorials/lns/2-frontend.adoc
  modules/ROOT/pages/tutorials/lns/4-tests.adoc
  modules/ROOT/pages/tutorials/lns/index.adoc
  modules/ROOT/pages/tutorials/nft.adoc
  modules/ROOT/pages/tutorials/srs.adoc
  modules/protocol/pages/accounts.adoc
  modules/protocol/pages/appendix.adoc
  modules/protocol/pages/blocks.adoc
  modules/protocol/pages/consensus-algorithm.adoc
  modules/protocol/pages/index.adoc
  modules/protocol/pages/transactions.adoc
Labels: type: update, component: lisk
