Repository LiskHQ/lisk-docs, pull requests merged in 2022-10, with the labels that each got.

#1639 Remove SDK Architecture from 'docs' - Closes 1509
  docs/modules/ROOT/pages/build-blockchain/configure-app.adoc
  docs/modules/ROOT/pages/understand-blockchain/sdk/architecture-pre1509-old.adoc
  docs/modules/ROOT/pages/understand-blockchain/sdk/rpc.adoc
Labels: component: lisk

#1638 Update Lisk SDK Overview page - Closes 1509
  modules/ROOT/pages/index.adoc
Labels: component: sdk

#1617 Update glossary terms in Lisk docs - Closes #1557
  docs/modules/ROOT/pages/glossary.adoc
Labels: type: update, component: lisk
