Repository LiskHQ/lisk-docs, pull requests merged in 2022-09, with the labels that each got.

#1611 Revamp `RPC API For Lisk Node` page - Closes 1538
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
Labels: component: lisk

#1618 Remove http-api-lisk-node from `Lisk Documentation` - Closes 1537
  build/.gitignore
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
Labels: component: lisk

#1619 Remove http api core from `docs-core` - Closes 1537
  modules/ROOT/pages/index.adoc
Labels: component: core

#1621 Updated SDK-->Application Cli - Closes 1540
  modules/ROOT/pages/application-cli.adoc
Labels: component: sdk

#1624 Updated `lisk-sdk/config.html` - Closes 1541
  modules/ROOT/pages/config.adoc
Labels: component: sdk

#1633 fixed wrong type in config.json #1630
  docs/modules/ROOT/pages/build-blockchain/configure-app.adoc
Labels: type: bug

#1634 wrong field number in "NFT Tutorial"
  docs/modules/ROOT/pages/tutorial/nft.adoc
Labels: type: bug
