Repository LiskHQ/lisk-docs, pull requests merged in 2022-04, with the labels that each got.

#1443 Create send tx guide - Closes #1258, #1428
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
  docs/modules/ROOT/pages/integrate-blockchain/decoding-transactions-blocks.adoc
  docs/modules/ROOT/pages/integrate-blockchain/send-transaction.adoc
Labels: component: lisk

#1441 Restructure API docs - Closes #1438
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/api/lisk-node-http.adoc
  docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
  docs/modules/ROOT/pages/build-blockchain/configure-app.adoc
  docs/modules/ROOT/pages/build-blockchain/create-module.adoc
  docs/modules/ROOT/pages/build-blockchain/using-dashboard.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/understand-blockchain/endpoints.adoc
  docs/modules/ROOT/pages/understand-blockchain/index.adoc
  docs/modules/ROOT/pages/understand-blockchain/modules-assets.adoc
  docs/modules/ROOT/pages/understand-blockchain/plugins.adoc
Labels: component: lisk

#1448 Update README - Closes #1432
  README.adoc
Labels: component: manual

#1452 Improve Lisk Service setup guide - Closes #1446
  modules/ROOT/pages/setup/docker.adoc
Labels: component: service

#1449 Update images for dark theme in service docs - Partially closes #1408
  modules/ROOT/assets/images/architecture.png
Labels: type: update, type: improvement, component: lisk
