Repository LiskHQ/lisk-docs, pull requests merged in 2023-07, with the labels that each got.

#1839 Add reference page for the base interoperability endpoints
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/api/module-rpc-api/interoperability-endpoints.adoc
  docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
Labels: component: lisk

#1821 Update connecting endpoints guide
  docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
  docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
Labels: type: update, component: lisk

#1840 Document endpoints for the PoS module - Closes 1723
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/api/module-rpc-api/pos-endpoints.adoc
  docs/modules/ROOT/pages/api/module-rpc-api/random-endpoints.adoc
Labels: component: lisk

#1841 Describe how to import old hash onion in Lisk docs
  docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
  docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
Labels: type: update, component: lisk

#1831 Service API migration reference
  docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
Labels: component: service, component: lisk

#1848 Mention using a different port when starting the app with the macOS in the nft tutorial in lisk docs
  docs/modules/ROOT/pages/tutorial/nft.adoc
Labels: type: update, component: lisk
