Repository LiskHQ/lisk-docs, pull requests merged in 2023-08, with the labels that each got.

#1854 Update "Example: Configuration for the Hello World client" - Closes 1850
  docs/modules/ROOT/pages/build-blockchain/configuration.adoc
Labels: component: lisk

#1852 Code snippet rendering error - 1835
  modules/ROOT/pages/config.adoc
Labels: component: sdk

#1860 Remove sentence to align with new structure in Lisk docs
  docs/modules/ROOT/pages/intro/lisk-products.adoc
Labels: type: update, component: lisk

#1861 Update Enabling Report Misbehavior plugin - Closes 1532
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
Labels: component: lisk

#1862 Create section describing wallet passphrase & security in Lisk docs
  docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
Labels: type: update, component: lisk
