Repository LiskHQ/lisk-docs, pull requests merged in 2023-01, with the labels that each got.

#1689 "Connecting to endpoints" guide - Closes 1583
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
Labels: component: lisk

#1694 Fix links in Core docs
  modules/ROOT/pages/index.adoc
Labels: component: core

#1693 Fix links in SDK docs
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/references/lisk-commander/cli.adoc
  modules/ROOT/pages/references/lisk-commander/index.adoc
  modules/ROOT/pages/references/migration.adoc
Labels: component: sdk

#1642 Update docker setup page - Closes #1605
  modules/ROOT/pages/index.adoc
Labels: type: update, component: lisk

#1640 Update configuration page in core docs - Closes #1560
  modules/ROOT/nav.adoc
  modules/ROOT/pages/management/configuration.adoc
Labels: type: update, component: lisk

#1687 Update source setup - closes #1606
  modules/ROOT/pages/setup/source.adoc
  modules/ROOT/partials/core-post-installation.adoc
Labels: type: update, component: lisk

#1704 Typo in method name of API client - closes 1631
  modules/ROOT/pages/references/lisk-elements/api-client.adoc
Labels: type: bug, component: lisk
