Repository LiskHQ/lisk-docs, pull requests merged in 2023-12, with the labels that each got.

#1505 Create blockchain interoperability page in Lisk docs - Closes #1497
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
Labels: type: feature, component: lisk

#1921 Update reward sharing guide in Lisk docs
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-0.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-00.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-01.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-02.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-03.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-04.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-05.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-1.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-2.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-3.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-4.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/claim-rewards-5.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-0.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-00.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-01.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-02.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-03.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-04.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-05.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-1.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-2.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-3.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-4.png
  docs/modules/ROOT/images/run-blockchain/reward-sharing/share-reward-5.png
  docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
Labels: type: update, component: lisk

#1925 Add the update.index.status.event to the Lisk service subscribe API page in Lisk docs
  docs/modules/ROOT/pages/api/lisk-service-pubsub.adoc
Labels: type: update, component: lisk

#1933 Add guide about extending Lisk Indexer service
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
Labels: component: lisk

#1935 Add links to lisk service related content
  docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/index.adoc
  docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
  docs/modules/ROOT/pages/run-blockchain/index.adoc
  docs/modules/ROOT/pages/understand-blockchain/index.adoc
Labels: component: lisk

#1932 New guide about monitoring a validator node
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
Labels: component: lisk

#1934 Fix formula for module store keys in Lisk docs
  docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
Labels: type: update, component: lisk

#1936 Copy to clipboard renders JSON incorrectly in Lisk docs
  docs/modules/ROOT/pages/run-blockchain/staking.adoc
Labels: type: bug, component: lisk

#1938 Add explanation about creating a bigger Hash Onion
  docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
Labels: component: lisk
