Repository LiskHQ/lisk-docs, pull requests merged in 2023-11, with the labels that each got.

#1904 Update managing logs page in Lisk docs
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/run-blockchain/logging.adoc
Labels: type: update, component: lisk

#1908 Update Multi-signature account registration guide - Closes 1880
  docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
Labels: component: lisk

#1913 Fix incorrect response in`chain_getGeneratorList` endpoint in Lisk docs
  docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
Labels: type: bug, component: lisk

#1914 Sign multisignature transactions offline - Closes 1260
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/integrate-blockchain/create-multiSig-tx-offline.adoc
Labels: component: lisk

#1916 Outdated pages should be removed - Closes 1891
  modules/ROOT/pages/actions.adoc
  modules/ROOT/pages/events.adoc
  modules/ROOT/pages/modules/dpos-module.adoc
  modules/ROOT/pages/modules/token-module.adoc
  modules/ROOT/pages/plugins/dashboard-plugin.adoc
  modules/ROOT/pages/plugins/faucet-plugin.adoc
  modules/ROOT/pages/plugins/forger-plugin.adoc
  modules/ROOT/pages/plugins/monitor-plugin.adoc
  modules/ROOT/pages/plugins/report-misbehavior-plugin.adoc
  modules/ROOT/pages/references/lisk-elements/api-client.adoc
  modules/ROOT/pages/references/lisk-elements/bft.adoc
  modules/ROOT/pages/references/lisk-elements/chain.adoc
  modules/ROOT/pages/references/lisk-elements/client.adoc
  modules/ROOT/pages/references/lisk-elements/codec.adoc
  modules/ROOT/pages/references/lisk-elements/cryptography.adoc
  modules/ROOT/pages/references/lisk-elements/db.adoc
  modules/ROOT/pages/references/lisk-elements/genesis.adoc
  modules/ROOT/pages/references/lisk-elements/p2p.adoc
  modules/ROOT/pages/references/lisk-elements/passphrase.adoc
  modules/ROOT/pages/references/lisk-elements/transaction-pool.adoc
  modules/ROOT/pages/references/lisk-elements/transactions.adoc
  modules/ROOT/pages/references/lisk-elements/tree.adoc
  modules/ROOT/pages/references/lisk-elements/utils.adoc
  modules/ROOT/pages/references/lisk-elements/validator.adoc
Labels: component: sdk

#1919 Remove outdated reference in Lisk docs index page
  docs/modules/ROOT/pages/run-blockchain/index.adoc
Labels: type: update, component: lisk
