Repository LiskHQ/lisk-docs, pull requests merged in 2025-03, with the labels that each got.

#289 [LISKDOCS-59] Indonesian Translation for [LISKDOCS-11] Add Remix guide
  README.md
  i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
  i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
  i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Remix.mdx
  i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
  i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
  i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.mdx
  i18n/ind/docusaurus-plugin-content-docs/current/partials/_remix-deploy-example.mdx
Labels: documentation

#290 [LISKDOCS-66] Correct heading level
  docs/building-on-lisk/add-token-to-lisk/index.md
  i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
Labels: bug

#287 [LISKDOCS-46] Remove metadata to enable automatic translation
  sidebars.js
Labels: maintenance

#294 [LISKDOCS-26] Align content and fix minor translation issues
  i18n/ind/code.json
  src/components/HomepageFeatures/index.js
  src/css/custom.css
  src/css/typography.css
Labels: maintenance
